name: PR Preview
on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
  pull_request:
    types: [labeled]

jobs:
  Release-Snapshot:
    runs-on: ubuntu-latest
    # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    if: ${{ github.event.label.name == 'preview-release' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          version: 14.x
      - name: Install Dependencies
        run: yarn
      - name: Exit prerelease mode if on
        run: |
          [ -f .changeset/pre.json ] && yarn changeset pre exit
      - name: Add changeset if there's none
        run: |
          if (find .changeset -name "*.md" ! -name "README.md" | grep .); then
             cp .github/changeset-samples/patch-all.md .changeset
          fi
          ls .changeset
          cat .changeset/patch-all.md
      - name: Run changeset version
        run: yarn changeset version --snapshot pr-${{ github.event.number }}
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            email=wkl.hyo@gmail.com
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to pr-# tag
        run: yarn changeset publish --tag pr-${{ github.event.number }}
      - name: "Comment on PR"
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            const message = `ðŸ“¦ We publshed this PR to \`pr-${issue_number}\` npm tag!`;
            github.issues.createComment({ issue_number, owner, repo, body: message });
      - name: Remove preview-release label
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            const label = 'preview-release';
            github.issues.removeLabel({ owner, repo, issue_number, name: label });
